drop table if exists `general_orders`;
create table `general_orders` (
	id	INT	 not null auto_increment,
	order_no	VARCHAR(512)	not null,
	user_id	INT	not null,
	op_id	VARCHAR(512)	,
	order_type	VARCHAR(512)	,
	order_status	VARCHAR(512)	not null,
	pay_status	VARCHAR(512)	not null,
	delivery_status	VARCHAR(512)	,
	products_id	INT	not null,
	quality	INT	not null,
	total_amount	DECIMAL(18,6)	not null,
	discount_amount	DECIMAL(18,6)	,
	shipping_fee	DECIMAL(18,6)	,
	actual_amount	DECIMAL(18,6)	not null,
	payment_channel	VARCHAR(512)	,
	payment_order_id	VARCHAR(512)	,
	payment_time	DATETIME	,
	payment_amount	DECIMAL(18,6)	,
	shipping_method	VARCHAR(512)	,
	shipping_address	VARCHAR(512)	,
	shipping_company	VARCHAR(512)	,
	tracking_number	VARCHAR(512)	,
	tel	VARCHAR(512)	,
	recipient	VARCHAR(512)	,
	create_time	DATETIME	not null,
	update_time	DATETIME	not null,
	cancel_time	DATETIME	,
	complete_time	DATETIME	,
	deliver_time	DATETIME	,
	refund_id	VARCHAR(512)	,
	refund_no	VARCHAR(512)	,
	refund_type	VARCHAR(512)	,
	refund_amount	DECIMAL(18,6)	,
	refund_reason	VARCHAR(512)	,
	refund_status	VARCHAR(512)	,
	remark	VARCHAR(512)	,
	is_deleted	INT	,
	table_name	VARCHAR(512)	,
	field_name	VARCHAR(512)	,
	primary key (id)
);