export const dynamicTabBars =[  {
    url: "/pagesA/home/index",
    text: "home",
    icon: "https://www.codeflying.net/preview/icon/home.png",
    onicon: "https://www.codeflying.net/preview/icon/select_home.png",
    title: "首页"
  },   {
    url: "/pagesA/inventory/index",
    text: "inventory",
    icon: "https://www.codeflying.net/preview/icon/notes.png",
    onicon: "https://www.codeflying.net/preview/icon/select_notes.png",
    title: "进销存"
  },   {
    url: "/pagesA/customer/index",
    text: "customer",
    icon: "https://www.codeflying.net/preview/icon/notes.png",
    onicon: "https://www.codeflying.net/preview/icon/select_notes.png",
    title: "客户"
  },   {
    url: "/pagesA/purchase/index",
    text: "purchase",
    icon: "https://www.codeflying.net/preview/icon/nav.png",
    onicon: "https://www.codeflying.net/preview/icon/select_nav.png",
    title: "采购"
  },   {
    url: "/pagesA/profile/index",
    text: "profile",
    icon: "https://www.codeflying.net/preview/icon/contact.png",
    onicon: "https://www.codeflying.net/preview/icon/select_contact.png",
    title: "个人信息"
  }]